#    server:
#      port:9090
#
#    spring:
#      datasource:
#        url: jdbc:postgresql://localhost:5432/microservice
#        username: postgres
#        password: root
#      jpa:
#        hibernate:
#          ddl-auto: update
#          show-sql: true

    server:
      port: 8002

    spring:
      data:
        mongodb:
          uri: mongodb://localhost:27017
          database: microservice2
      application:
        name: HOTEL-SERVICE
      config:
        import: optional:configserver:http://localhost:8005

#    eureka:
#      instance:
#        prefer-ip-address: true
#      client:
#        fetch-registry: true
#        register-with-eureka: true
#        service-url:
#          defaultZone: http://localhost:8761/eureka
